py3: fix exception upon login
TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Inaky Perez-Gonzalez <inaky.perez-gonzalez@intel.com>