ttbl.raritan_emx: fix generation of the URL property
When storing the original URL in the file system DB, we were storing
:None if we had specified no port in outlet_number, which was then
messing up the using later on manifesting as:

  WARNING[56608] power._execute_action():3291: target-TARGETNAME: ttbl.power._execute_action(): powering on
  ERROR[56608] raritan_emx._raritan_api_handle_create():311: target-TARGETNAME: raritan: TARGETNAME exception creating handle: Port could not be cast to integer value as 'None'
  Traceback (most recent call last):
    File "/usr/lib/python3.12/site-packages/ttbl/raritan_emx.py", line 296, in _raritan_api_handle_create
      url, password, outlet_number = self._url_resolve(url_base, password)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/ttbl/raritan_emx.py", line 273, in _url_resolve
      if url.port:
         ^^^^^^^^
    File "/usr/lib64/python3.12/urllib/parse.py", line 182, in port
      raise ValueError(f"Port could not be cast to integer value as {port!r}")
  ValueError: Port could not be cast to integer value as 'None'

whe creating the driver as

  ttbl.raritan_emx.pci("URL:PORTNUMBER")