tcf: rename --password to --environment-password
--password was conflicting with --password for tcf login and other
subcommands that do a password in the command line and causing errors
when trying to login using credentials from environment:

  $ tcf.git/tcf login --quiet
  Traceback (most recent call last):
    File ".../tcf.git/tcf", line 331, in <module>
      for environment in args.password:
  TypeError: 'NoneType' object is not iterable

So to avoid that, since it is a conflict of namespace, rename it to
--environment-password.

Signed-off-by: Inaky Perez-Gonzalez <inaky.perez-gonzalez@intel.com>